# see: https://golangci-lint.run/
# reference: https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
run:
  deadline: 5m

issues:
  # golangci-lintがdefaultで無効にしているlintersを有効にする
  # exclude-use-default: false
  exclude-dirs:
    - node_modules

# linters-settings:
linters:
  disable-all: true
  enable:
    - goimports
    - revive
    - govet
    - gosec
    - misspell
    - errcheck
    - staticcheck
    - prealloc
    - ineffassign
  exclude:
    - node_modules/**/*
