# Assignees, Reviewers を自動設定する
name: auto-assign
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  add-reviews:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/configs/auto_assign.yml"
