name: Auto Pull Request prod

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"

jobs:
  create-pr-prod:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: create PR if not exists
        run: |
          if ! gh pr list -B main | grep OPEN; then
            gh pr create \
              --head develop \
              --base main \
              --title "Deploy to production 🎉" \
              --body "Deploy to production!" \
              --reviewer naohito-T
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
