name: Test Backend

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/test_backend.yml"
      - '!**.md'

defaults:
  run:
    working-directory: backend

jobs:
  lint-backend:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        id: setup-go
        with:
          go-version-file: "backend/go.mod"
          cache-dependency-path: "backend/go.sum"

      - name: Download Go modules
        shell: bash
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        run: go mod download

      - name: Lint check
        run: make lint

      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2022.1.3"
          install-go: false
          working-directory: backend

  build-backend:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        id: setup-go
        with:
          go-version-file: "backend/go.mod"
          cache-dependency-path: "backend/go.sum"

      - name: Download Go modules
        shell: bash
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        run: go mod download

      - name: Build check
        run: GOARCH=arm64 GOOS=linux go build -ldflags="-s -w"
